services:
  r-studio:
    container_name: r-studio
    build: 
      context: .
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    image: r-studio
    environment:
      - DISABLE_AUTH=true
      - USERID=${UID:-1000}
      - GROUPID=${GID:-1000}
      - PASSWORD=pswd
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/workspace
      - renv:/home/rstudio/.cache/R/renv
volumes:
  renv:
    external: true
 
